//user reducer types
export const SIGNUP_USER = 'SIGNUP_USER' 
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER' 
export const LOADING_USER = 'LOADING_USER' 
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED' 
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED' 
export const SET_ALL_USER = 'SET_ALL_USER' 
export const EDIT_USER_DETAILS = 'EDIT_USER_DETAILS' 

//ui reducer types
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS' 
export const MARK_ALL_READ = 'MARK_ALL_READ' 
export const SET_PREV_MONTH = 'SET_PREV_MONTH' 
export const SET_NEXT_MONTH = 'SET_NEXT_MONTH' 

//data reducer types
export const LOADING_DATA = 'LOADING_DATA'
//admin
export const SET_USERS = 'SET_USERS'
export const SET_REQUESTS = 'SET_REQUESTS'
export const SET_VACCINE_CENTER = 'SET_VACCINE_CENTER'
//general user
export const GET_VACCINE_CENTERS = 'GET_VACCINE_CENTERS'
export const SELECTED_CENTER = 'SELECTED_CENTER'
export const GET_DAILY_STOCK = 'GET_DAILY_STOCK'
export const BOOK_APPOINTMENT = 'BOOK_APPOINTMENT'
export const EDIT_APPOINTMENT = 'EDIT_APPOINTMENT'
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT'
export const POST_FEEDBACK = 'POST_FEEDBACK'
